DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_chamba;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_badrinath;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_swargashramjonk;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_narendranagar;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_dugadda;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_lohaghat;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_kotdwar;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_chamoligopeshwar;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_joshimath;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_manglaur;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_mussorie;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_ramnagar;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_rudraprayag;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_vikasnagar;

CREATE SEQUENCE seq_eg_pt_ptid_uk_swargashramjonk;
CREATE SEQUENCE seq_eg_pt_ptid_uk_narendranagar;
CREATE SEQUENCE seq_eg_pt_ptid_uk_dugadda;
CREATE SEQUENCE seq_eg_pt_ptid_uk_chamba;
CREATE SEQUENCE seq_eg_pt_ptid_uk_badrinath;
CREATE SEQUENCE seq_eg_pt_ptid_uk_lohaghat;
CREATE SEQUENCE seq_eg_pt_ptid_uk_kotdwar;
CREATE SEQUENCE seq_eg_pt_ptid_uk_chamoligopeshwar;
CREATE SEQUENCE seq_eg_pt_ptid_uk_joshimath;
CREATE SEQUENCE seq_eg_pt_ptid_uk_manglaur;
CREATE SEQUENCE seq_eg_pt_ptid_uk_mussorie;
CREATE SEQUENCE seq_eg_pt_ptid_uk_ramnagar;
CREATE SEQUENCE seq_eg_pt_ptid_uk_rudraprayag;
CREATE SEQUENCE seq_eg_pt_ptid_uk_vikasnagar;
