DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_chamba;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_badrinath;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_swargashramjonk;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_narendranagar;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_dugadda;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_lohaghat;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_kotdwar;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_chamoligopeshwar;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_joshimath;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_manglaur;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_mussorie;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_ramnagar;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_rudraprayag;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_vikasnagar;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_herbertpur;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_berinag;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_pirankaliyar;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_bhimtal;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_champawat;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_nainital;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_jhabrera;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_kaladhungi;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_karnaprayag;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_lalkuan;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_mahuwadawara;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_munikireti;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_nandprayag;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_srinagar;

CREATE SEQUENCE seq_eg_pt_ptid_uk_swargashramjonk;
CREATE SEQUENCE seq_eg_pt_ptid_uk_narendranagar;
CREATE SEQUENCE seq_eg_pt_ptid_uk_dugadda;
CREATE SEQUENCE seq_eg_pt_ptid_uk_chamba;
CREATE SEQUENCE seq_eg_pt_ptid_uk_badrinath;
CREATE SEQUENCE seq_eg_pt_ptid_uk_lohaghat;
CREATE SEQUENCE seq_eg_pt_ptid_uk_kotdwar;
CREATE SEQUENCE seq_eg_pt_ptid_uk_chamoligopeshwar;
CREATE SEQUENCE seq_eg_pt_ptid_uk_joshimath;
CREATE SEQUENCE seq_eg_pt_ptid_uk_manglaur;
CREATE SEQUENCE seq_eg_pt_ptid_uk_mussorie;
CREATE SEQUENCE seq_eg_pt_ptid_uk_ramnagar;
CREATE SEQUENCE seq_eg_pt_ptid_uk_rudraprayag;
CREATE SEQUENCE seq_eg_pt_ptid_uk_vikasnagar;
CREATE SEQUENCE seq_eg_pt_ptid_uk_herbertpur;
CREATE SEQUENCE seq_eg_pt_ptid_uk_berinag;
CREATE SEQUENCE seq_eg_pt_ptid_uk_pirankaliyar;
CREATE SEQUENCE seq_eg_pt_ptid_uk_bhimtal;
CREATE SEQUENCE seq_eg_pt_ptid_uk_champawat;
CREATE SEQUENCE seq_eg_pt_ptid_uk_nainital;
CREATE SEQUENCE seq_eg_pt_ptid_uk_jhabrera;
CREATE SEQUENCE seq_eg_pt_ptid_uk_kaladhungi;
CREATE SEQUENCE seq_eg_pt_ptid_uk_karnaprayag;
CREATE SEQUENCE seq_eg_pt_ptid_uk_lalkuan;
CREATE SEQUENCE seq_eg_pt_ptid_uk_mahuwadawara;
CREATE SEQUENCE seq_eg_pt_ptid_uk_munikireti;
CREATE SEQUENCE seq_eg_pt_ptid_uk_nandprayag;
CREATE SEQUENCE seq_eg_pt_ptid_uk_srinagar; 
