DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_chamba;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_badrinath;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_swargashramjonk;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_narendranagar;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_dugadda;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_lohaghat;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_kotdwar;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_chamoligopeshwar;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_joshimath;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_manglaur;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_mussorie;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_ramnagar;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_rudraprayag;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_vikasnagar;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_herbertpur;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_berinag;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_pirankaliyar;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_bhimtal;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_uttarkashi;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_bageshwar;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_champawat;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_dwarahat;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_pauri;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_nainital;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_pithoragarh;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_doiwala;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_didihat;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_gauchar;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_dineshpur;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_augustmuni;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_dharchula;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_gairsain;
DROP SEQUENCE IF EXISTS seq_eg_pt_ptid_uk_bazpur;

CREATE SEQUENCE seq_eg_pt_ptid_uk_swargashramjonk;
CREATE SEQUENCE seq_eg_pt_ptid_uk_narendranagar;
CREATE SEQUENCE seq_eg_pt_ptid_uk_dugadda;
CREATE SEQUENCE seq_eg_pt_ptid_uk_chamba;
CREATE SEQUENCE seq_eg_pt_ptid_uk_badrinath;
CREATE SEQUENCE seq_eg_pt_ptid_uk_lohaghat;
CREATE SEQUENCE seq_eg_pt_ptid_uk_kotdwar;
CREATE SEQUENCE seq_eg_pt_ptid_uk_chamoligopeshwar;
CREATE SEQUENCE seq_eg_pt_ptid_uk_joshimath;
CREATE SEQUENCE seq_eg_pt_ptid_uk_manglaur;
CREATE SEQUENCE seq_eg_pt_ptid_uk_mussorie;
CREATE SEQUENCE seq_eg_pt_ptid_uk_ramnagar;
CREATE SEQUENCE seq_eg_pt_ptid_uk_rudraprayag;
CREATE SEQUENCE seq_eg_pt_ptid_uk_vikasnagar;
CREATE SEQUENCE seq_eg_pt_ptid_uk_herbertpur;
CREATE SEQUENCE seq_eg_pt_ptid_uk_berinag;
CREATE SEQUENCE seq_eg_pt_ptid_uk_pirankaliyar;
CREATE SEQUENCE seq_eg_pt_ptid_uk_bhimtal;
CREATE SEQUENCE seq_eg_pt_ptid_uk_uttarkashi;
CREATE SEQUENCE seq_eg_pt_ptid_uk_bageshwar;
CREATE SEQUENCE seq_eg_pt_ptid_uk_champawat;
CREATE SEQUENCE seq_eg_pt_ptid_uk_dwarahat;
CREATE SEQUENCE seq_eg_pt_ptid_uk_pauri;
CREATE SEQUENCE seq_eg_pt_ptid_uk_nainital;
CREATE SEQUENCE seq_eg_pt_ptid_uk_pithoragarh;
CREATE SEQUENCE seq_eg_pt_ptid_uk_doiwala;
CREATE SEQUENCE seq_eg_pt_ptid_uk_didihat;
CREATE SEQUENCE seq_eg_pt_ptid_uk_gauchar;
CREATE SEQUENCE seq_eg_pt_ptid_uk_dineshpur;
CREATE SEQUENCE seq_eg_pt_ptid_uk_augustmuni;
CREATE SEQUENCE seq_eg_pt_ptid_uk_dharchula;
CREATE SEQUENCE seq_eg_pt_ptid_uk_gairsain;
CREATE SEQUENCE seq_eg_pt_ptid_uk_bazpur;
